# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
import json
from ccxt.base.errors import ExchangeError


class kabus(Exchange):

    def describe(self):
        return self.deep_extend(super(kabus, self).describe(), {
            'id': 'kabus',
            'name': 'Kabus',
            'countries': ['JP'],
            'version': 'v1',
            'rateLimit': 1000,
            'timeframes': {
                '1m': '1m',
                '3m': '3m',
                '5m': '5m',
                '15m': '15m',
                '30m': '30m',
                '1h': '1h',
                '2h': '2h',
                '4h': '4h',
                '6h': '6h',
                '8h': '8h',
                '12h': '12h',
                '1d': '1d',
                '3d': '3d',
                '1w': '1w',
                '1M': '1M',
            },
            'urls': {
                'logo': 'https://pbs.twimg.com/profile_images/1476235905375813633/-jRNbwhv_400x400.jpg',
                'api': 'http://{ipaddr}/live/kabusapi',
                'www': 'https://twitter.com/KabutoTheBot',
                'doc': 'https://twitter.com/KabutoTheBot',
            },
            'has': {
                'CORS': None,
                'spot': True,
                'margin': None,
                'swap': None,
                'future': None,
                'option': None,
                'fetchBalance': True,
                'fetchOHLCV': True,
                'fetchOrderBook': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'registerWhitelist': True,
            },
            'precision': {
                'amount': -2,
                'price': None,
            },
            'api': {
                'public': {
                    'get': [
                        'board/{symbol}',
                    ],
                    'post': [
                        'token',
                    ],
                    'put': [
                        'register',
                    ],
                },
                'private': {
                    'get': [
                        'wallet/cash',
                    ],
                },
            },
            'requiredCredentials': {
                'ipaddr': True,
                'password': False,
                'apiKey': False,
                'secret': False,
                'uid': False,
                'login': False,
                'twofa': False,  # 2-factor authentication(one-time password key)
                'privateKey': False,  # a "0x"-prefixed hexstring private key for a wallet
                'walletAddress': False,  # the wallet address "0x"-prefixed hexstring
                'token': False,  # reserved for HTTP auth in some cases
            },
            'fees': {
                'trading': {
                    'maker': self.parse_number('0.0'),
                    'taker': self.parse_number('0.0'),
                },
            },
        })

    async def fetch_markets(self, params={}):
        # Return a list of stock code and its basic properties for trading
        # No API access for now
        markets = [
            '8306@1',
            '4689@1',
            '6501@1',
            '3826@1',
            '5020@1',
            '3632@1',
            '5191@1',
            '6440@1',
            '8897@1',
            '167060018@24',
        ]
        result = []
        for i in range(0, len(markets)):
            result.append({
                'id': i,
                'symbol': markets[i] + '/JPY',
                'base': 'JPY',
                'quote': 'JPY',
                'maker': 0.001,
                'taker': 0.001,
                'active': True,
                'min_unit': 100,
                # value limits when placing orders on self market
                'limits': {
                    'amount': {
                        # order amount should be > min
                        'min': 100,
                        # order amount should be < max
                        'max': 100000000,
                    },
                    'price': {
                        'min': 100,
                        'max': 100000000,
                    },
                    # order cost = price * amount
                    'cost': {
                        'min': 0,
                        'max': 100000000,
                    },
                },
            })
        return result

    def parse_balance(self, response):
        # Parse and organize balance information.
        result = {'info': response}
        account = self.account()
        account['free'] = self.safe_float(response, 'StockAccountWallet')
        result['JPY'] = account
        return result

    async def fetch_balance(self, params={}):
        # Fetch account balance information
        await self.load_markets()
        response = await self.privateGetWalletCash(params)
        # {
        #      'StockAccountWallet': '497120.0'
        # }
        return self.parse_balance(response)

    async def fetch_trades(self, symbol, since=None, limit=None, params={}):
        await self.load_markets()
        return []

    async def fetch_ticker(self, symbol, params={}):
        # Fetch board informatio of a single symbol.
        await self.load_markets()
        symbol = symbol[0:-4]
        request = {
            'symbol': symbol,
        }
        return self.publicGetBoardSymbol(self.extend(request, params))

    async def fetch_tickers(self, symbol, params={}):
        # Coming soon
        return None

    async def fetch_order_book(self, symbol, limit=None, params={}):
        # Fetch order book information of a single symbol
        ticker = await self.fetch_ticker(symbol, params)
        keys = list(ticker.keys())
        buys = []
        sells = []
        for i in range(0, len(keys)):
            key = keys[i]
            if key.find('Buy') == 0:
                buys.append([ticker[key]['Price'], ticker[key]['Qty']])
            if key.find('Sell') == 0:
                sells.append([ticker[key]['Price'], ticker[key]['Qty']])
        orderbook = {'bids': buys, 'asks': sells}
        return self.parse_order_book(orderbook, symbol)

    async def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=None, params={}):
        # Fetch latest OHLCV data of a single symbol from the local PriceServer
        symbol = symbol[0:-4]
        response = await self.fetch('http://127.0.0.1:8999/charts/' + symbol + '/JPY/1m', 'GET')
        ohlcvs = json.loads(response[symbol])
        data = []
        for i in range(0, len(ohlcvs)):
            data.append(ohlcvs[i][0:-1])
        return data

    def fetch_token(self):
        # Fetch one-time access token for Kabus API
        url = self.implode_params(self.urls['api'], {'ipaddr': self.ipaddr}) + '/token'
        headers = {
            'Content-Type': 'application/json',
        }
        # json.loads() is needed to load json module in transpiled Python script
        body = json.dumps({'APIPassword': self.password})
        response = self.fetch(url, 'POST', headers, body)
        if response['ResultCode'] == '0':
            return response['Token']
        else:
            # Temporary placeholder for exception when it fails to get a new token
            raise ExchangeError()

    def parse_ticker(self, pair):
        # Parse ticker string to get symbol and exchange code
        identifier = pair.split('/')[0]
        symbol = identifier.split('@')[0]
        exchange = int(identifier.split('@')[1])
        return {'Symbol': symbol, 'Exchange': exchange}

    async def register_whitelist(self, whitelist):
        # Register whitelist symbols.
        # FIXME: This cannnot be use from Worker due to the nature of the bot process.
        # PriceServer has a function for the same purpose and that is used instead.
        symbols = {'Symbols': []}
        for i in range(0, len(whitelist)):
            tickerVal = self.parse_ticker(whitelist[i])
            symbols['Symbols'].append(tickerVal)
        body = json.dumps(symbols)
        response = self.fetch2('register', 'public', 'PUT', {}, None, body, {}, {})
        return response['RegistList']

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        # Attach header and other necessary parameters to the API request.
        # This is called before a REST API request thrown to the server.
        # TODO: Handle differently 'public' call and 'private' call to improve security.
        self.check_required_credentials()
        if not self.apiKey:
            self.apiKey = self.fetch_token()
        request = '/' + self.implode_params(path, params)
        url = self.implode_params(self.urls['api'], {'ipaddr': self.ipaddr}) + request
        headers = {
            'X-API-KEY': self.apiKey,
            'Content-Type': 'application/json',
        }
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
